#!/bin/bash
# dependências "yad"

yad --center --width=400 --height=100 --title= "AVISO" \  --text="Execute usando o comando  ' sudo ' \ 
ou o logado com usuário ' root ' para executar este software! "  --button=gtk-ok:0
exit 1
fi

yad --center --width=400 --height=100 --text="Caso não tenha respositórios necessários como RPMFusion o mesmo irá instalar " --button=gtk-ok:0

ls /etc/yum.repos.d/ > /tmp/repo
rpmfusion=$(grep rpmfusion /tmp/repo )
home=$(grep home /tmp/repo )

if [ -n "$rpmfusion" ] ;
then 
     yad --center --width=400 --height=100 --text="Rpmfusion já instaldo" --button=gtk-ok:0
else
   dnf -y --nogpgcheck install http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
   dnf -y --nogpgcheck install http://download1.rpmfusion.org/free/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

fi

if [ -n "$home" ] ;
 then
 yad --center --width=400 --height=100 --text="Repositório Emulador WII já instaldo" --button=gtk-ok:0
else
 cd /etc/yum.repos.d/
 wget http://download.opensuse.org/repositories/home:/KAMiKAZOW:/Fedora/Fedora_22/home:KAMiKAZOW:Fedora.repo
exit 1
fi

INSTALL=$(yad --center --form --width=400 --height=500 --title "Instalar Emuladores, Jogos e Steam" \
 --field "Atari:CHK" \
 --field "Nes:CHK" \
 --field "Master Sytem - GameGear:CHK" \
 --field "MegaDriver - 32X - SegaCD:CHK" \
 --field "SuperNes:CHK" \
 --field "GameBoy, GameBoy-Color, GameBoy-Advance:CHK" \
 --field "N64:CHK" \
 --field "PS1:CHK" \
 --field "PS2:CHK" \
 --field "PSP:CHK" \
 --field "Sega Saturn:CHK" \
 --field "Dreamcast:CHK" \
 --field "Wii , GameGube:CHK" \
 --field "Arcade M.A.M.E:CHK" \
 --field "Steam:CHK" \
 --field "Fedora Games:CHK" \
 ""); 
echo "$INSTALL" > /tmp/tmp
 STELLA=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $1 }' )
 NES=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $2 }' )
 MASTER=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $3 }' )
 MEGA=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $4 }' )
 SNES=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $5 }' )
 GAMEBOY=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $6 }' )
 N64=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $7 }' )
 PS1=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $8 }' )
 PS2=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $9 }' )
 PSP=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $10 }' )
 SATURN=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $11 }' )
 DREAM=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $12 }' )
 WII=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $13 }' )
 MAME=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $14 }' )
 STEAM=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $15 }' )
 FG=$(cat /tmp/tmp | awk 'BEGIN { FS="|" } { print $16 }' )

 if [ "$STELLA" = "TRUE" ]; then
    dnf install stella -y
fi

 if [ "$NES" = "TRUE" ]; then
    dnf install Nestopia -y
fi

 if [ "$NES" = "TRUE" ]; then
    dnf install osmose -y
fi

 if  [ "$MEGA" = "TRUE" ]; then
    dnf install gens -y
fi

 if [ "$SNES" = "TRUE" ]; then
    dnf install snes9x -y
fi

 if [ "$GAMEBOY" = "TRUE" ]; then
    dnf install vbam-gtk -y
fi
   if [ "$N64" = "TRUE" ]; then
    dnf install mupen64plus m64py -y
fi

if [ "$PS1" = "TRUE" ]; then
    dnf install pcsxr -y
fi

 if [ "$PS2" = "TRUE" ]; then
    dnf install pcsx2 -y
fi

 if [ "$PSP" = "TRUE" ]; then
    dnf install ppsspp-dev -y
fi

 if [ "$SATURN" = "TRUE" ]; then
    dnf install yabause -y
fi

 if [ "$DREAM" = "TRUE" ]; then
    dnf install lxdream -y
fi

 if [ "$WII" = "TRUE" ]; then
    dnf install dolphin-emu dolphin-emu-lang.noarch dolphin-emu-nogui -y
fi

 if [ "$MAME" = "TRUE" ]; then
    dnf install mame qmc2-sdlmame -y
fi
 
 if [ "$STEAM" = "TRUE" ]; then
    dnf install steam -y
fi

  if [ "$FG" = "TRUE" ]; then
    dnf groupinstall "Games and Entertainment" -y

 else 
  echo "erro"
fi
